### ISSUE TITLE
Changing after meeting

### ISSUE THREAD

**Issue by BMD91** [aPissarek/webapp22-pissarek#10]
I did change some information in my design: 
+ Pupils won't need any information about their age, because it can be provided through their date of birth.
+ Teachers should be given information about their phone number, in case parents want to contact them.

**Comment by aPissarek** [comment]
I am hereby confirming your model. However,  a few things I have noticed, which I would recommend to change, are:
- studentNumber should be: numOfStudents to avoid confusion (actually numOfPupils, since you chose the British word)
- "averagePoint" should be gradeAverage
- the value of the class level should be between 1 and 4 (invariant constraint) but not the multiplicity, multiplicity is 1
- numOfPupils should also be a positive integer, like the other integer properties

**Comment by BMD91** [comment]
Yes, as your requirement I did change it.
