### ISSUE TITLE
Grade of pupils

### ISSUE THREAD

**Issue by BMD91** [aPissarek/webapp22-pissarek#7]
As in your description, I can see that, you are running an elementary school. I am not sure about the type of grades, which your pupils will be given. Are they in number (from 1 to 5 as German standard or from 0 to 10 as international grades) or in letter with A, B, C, D, F likes many other schools?

**Comment by aPissarek** [comment]
We usually use a grading system from 1 to 5 as in Germany, since the students and classes data should feature a grade average: each student has his/her own average grade and the class has the average grade of all students. This average should have 1 digit behind the comma. This would be difficult using a mapping to letters.

**Comment by BMD91** [comment]
Thank you for that information.
